language: node_js
node_js: "node"
before_deploy:
- openssl aes-256-cbc -K $encrypted_8a7195b71fd2_key -iv $encrypted_8a7195b71fd2_iv -in deploykey.enc -out deploykey -d
- chmod 600 deploykey
- mv deploykey ~/.ssh/id_rsa
- echo -e "Host perala.me\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  skip_cleanup: true
  provider: script
  script: rsync -r --delete dist/ deploy@perala.me:~/kmbmpdc
  on:
    branch: master
